### ISSUE TITLE
No longer working with svgz

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-hotgrid#104]
Hotgrid v4.3.4 is not longer showing the notify popo when using svgz images using the Graphic Lottie plugin (https://github.com/cgkineo/adapt-graphicLottie)

We have tested using standard png/jpg and the notify box displays on click, but not when using svgz as either the item graphic or popup graphic the notify popup is not working.

### Your environment
* version (AT 0.11.1/Framework 5.25.2)
* Safari v16.2
* macOS 13.1

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
As per expected screen shot

### Actual behaviour
Tell us what happens instead

### Screenshots (if you can)
![2023-02-14_14-41-20](https://user-images.githubusercontent.com/29701150/218770468-42cc85e4-b453-4bee-bbf3-197da681c66f.jpg)
![Expected](https://user-images.githubusercontent.com/29701150/218770898-e23d7e82-6981-412a-8722-4b8b9057efec.jpg)

**Comment by kirsty-hames** [comment]
Closing as the issue has been raised for graphicLottie plugin. As per my [comment](https://github.com/cgkineo/adapt-graphicLottie/issues/13#issuecomment-1632660240), this issue isn't specific to Hotgrid.

**Comment by fosterc1** [comment]
Hello Kirsty

I may have misunderstood, but I though you said this was related to Hotgrid and Hotgraphic:
I can replicate the issue described for both Hotgrid and Hotgraphic. No console errors to report.

Using svgz in question feedback however works as expected so I don't think this issue is global to Notify. Both Hotgrid and Hotgraphic have their own popup template so the issue might be specific to this.

Cheers
