### ISSUE TITLE
Responsive item width inconsistency 

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-hotgrid#118]
### Subject of the issue
When viewing Hotgrid below `screenSize` `large` items are set to `width: 100%` via [JS](https://github.com/cgkineo/adapt-hotgrid/blob/728b2a24ac85f082c56f524ffa03de3c166bee06/js/HotgridView.js#L43). The default item width is defined as `width: 50%` in the [LESS](https://github.com/cgkineo/adapt-hotgrid/blob/728b2a24ac85f082c56f524ffa03de3c166bee06/less/hotgrid.less#L10) but this is always overruled via the inline style.

### Expected behaviour
I'd expect the inline style to only apply when `screenSize` is `large` and inherit from the LESS otherwise. This would also be consistent with GMCQ which also uses [_columns](https://github.com/adaptlearning/adapt-contrib-gmcq/blob/53c5724364f3c416c0eae24ac8992104e05ea256/templates/gmcq.jsx#L58-L60).

### Actual behaviour
Whilst items display at `width: 100%` below `screenSize` `large` we end up with items display up to 4 times larger than their desktop display (depending on your `_column` setup). Ideally we should be maintaining the item size or scaling down, not bigger.

Screen shot at `screenSize` `large`:
<img width="744" alt="screensize_large" src="https://user-images.githubusercontent.com/7045330/235933489-6624879a-bb1c-4f79-bfe6-9f591f01aee6.png">
Screen shot below `screenSize` `large`:
<img width="733" alt="below_screensize_large" src="https://user-images.githubusercontent.com/7045330/235933563-5abdcc12-912f-47d0-9304-46761f4c7121.png">

**Comment by StuartNicholls** [comment]
Didn't we hold off making changes here pending a discussion about how we are going to handle columns generally going forward? I think @swashbuck raised it previously? Re. inline style, whatever the way forward we should really be using classes rather than explicitly stating a width inline.

**Comment by kirsty-hames** [comment]
> Didn't we hold off making changes here pending a discussion about how we are going to handle columns generally going forward? I think @swashbuck raised it previously? Re. inline style, whatever the way forward we should really be using classes rather than explicitly stating a width inline.

Yep that's right (#98) which is rework of the component and I agree we should be using CSS/media queries not inline style.

I'm just flagging an error with the current implementation which I'm assuming is an oversight and the width should be 50%  (as per the CSS) or null (and inherit from the CSS).

**Comment by swashbuck** [comment]
@kirsty-hames This makes sense to me. I'm in favor of aligning Hot Grid columns with how they work in Hot Graphic. #98 will take more time to implement, but this would be an easy win until that's ready.
