### ISSUE TITLE
Remove plus icon that appears when graphic title is not present

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-hotgrid#119]
### Subject of the issue
This came up on the [Add completion icon styles PR](https://github.com/cgkineo/adapt-hotgrid/pull/117) so just copying the discussion over...

> This has scope creeped quite some. Please update the title+description or move the icon removal to a different pr+issue. Perhaps the icon should just be configurable rather than removed? It's been there since 2019.

Making the icon configurable would mean we still have the issue of duplicate icons.
<img width="793" alt="icon__duplication" src="https://user-images.githubusercontent.com/7045330/234823524-6f380e67-894e-4391-a694-1e5d9d4dd678.png">

`.hotgrid__item-icon` was added following a project where the clients brand didn't allow for borders around images so another element was needed to apply the state changes (inherit button states). 
<img width="898" alt="no_borders" src="https://user-images.githubusercontent.com/7045330/234828138-703ffe98-ae91-4ce1-b385-acf1161f84c7.png">

The current implementation of Hotgrid only supports CSS border states or images states. So unless you do custom CSS to remove the borders the original issue `.hotgrid__item-icon` was trying to solve was half baked. With that in mind, @StuartNicholls/@swashbuck, perhaps it's worth reviewing the display/state options in a separate PR. There is definitely a use case for removing `.hotgrid__item-icon` as this is often requested however a config option to allow for no border with plus icon could be useful?

Other reasons raised:
- This regularly gets requested to be removed in projects.
- It doesn't really communicate that its clickable other than it's similar to Hotgraphic.

**Comment by swashbuck** [comment]
For the "plus" icon, when completed, that could just become a checkmark (instead of a plus) just like the Hot Graphic does. Then, we wouldn't show the other completion icon from #99

**Comment by kirsty-hames** [comment]
> For the "plus" icon, when completed, that could just become a checkmark (instead of a plus) just like the Hot Graphic does. Then, we wouldn't show the other completion icon from #99

Sounds good to me thanks @swashbuck. For consistency with #117, I think we should reduce `.hotgrid__item-icon` padding to `@item-padding / 2` also?

**Comment by swashbuck** [comment]
Thanks, @kirsty-hames . I think we can probably do all of this work in the #117 PR then, since we decided to not remove the plus icon. Agreed?

**Comment by swashbuck** [comment]
Included the padding change in #117

**Comment by swashbuck** [comment]
@kirsty-hames @StuartNicholls Do you think we need a config option to hide the plus icon when no title is used? If so, that can be handled on this ticket. Otherwise, we can probably close it.

**Comment by StuartNicholls** [comment]
To be honest, I would have removed it altogether. If we're keeping it, I'd say yes to config option, but off by default. But happy the other way too.

**Comment by swashbuck** [comment]
> yes to config option, but off by default

This sounds good to me. So, maybe a component-level (not item-level) property like:

**Show plus icon when item has no title**
**_hasIconWhenNoTitle:** false (default)
