### ISSUE TITLE
item doesn't clear due to length of title above it

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-hotgrid#21]
Notice in the first image, the title "I'll just wing it." is one line as opposed to the title of its neighbor to the left which is two lines. 
![screen shot 2016-10-10 at 11 17 50 pm](https://cloud.githubusercontent.com/assets/9489014/19258836/7928d2d2-8f41-11e6-9d1b-9553a8a69c44.png)

Increasing the amount of "wing it" text to force another line permits the items to fall in line.

![screen shot 2016-10-10 at 11 19 04 pm](https://cloud.githubusercontent.com/assets/9489014/19258868/cf34aa48-8f41-11e6-9bf6-08b530d9742a.png)

(Columns are set to 3.)

**Comment by guywillis** [comment]
As of v5 the above issue is resolved due to the removal of floats and the introduction of flex.
