### ISSUE TITLE
Not working in AT

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-hotgrid#25]
Needs this added to schema:

"_supportedLayout": {
      "type": "string",
      "required": true,
      "enum": ["full-width", "half-width", "both"],
      "default": "half-width",
      "editorOnly": true
},

**Comment by moloko** [comment]
done in https://github.com/cgkineo/adapt-hotgrid/commit/55d07c86e664d96e2eff507fc3bf53de9372d6ed - thanks @simondate
