### ISSUE TITLE
Prevents pages from load in IE when the images are not included

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-hotgrid#27]
Unlike with other components, when images are not included in the build, this component will not call `setReadyStatus` for IE (IE11 at least). Other browsers seem to work fine.

**Comment by oliverfoster** [comment]
what's the date at the top of the core/js/libraries/imageReady.js file?

**Comment by danielghost** [comment]
//https://github.com/adaptlearning/jquery.imageready 2017-05-09

**Comment by oliverfoster** [comment]
can you dump the json config for just the component in here?

**Comment by moloko** [comment]
closing as unlikely to still be relevant
