### ISSUE TITLE
Doesnt work in ie8 with Adapt 2.0

### ISSUE THREAD

**Issue by robmausser** [cgkineo/adapt-hotgrid#35]
This component does not work in ie8, as the images to click on do not show up.

**Comment by moloko** [comment]
seems fine to me...
![hotgrid-ie8](https://user-images.githubusercontent.com/1249597/35861826-583b54aa-0b41-11e8-84d4-f29d64e0197b.png)

![hotgrid-ie8-clicked](https://user-images.githubusercontent.com/1249597/35861830-61940c72-0b41-11e8-989f-a3143e18308d.png)
