### ISSUE TITLE
Hot grid - missing labels on DT close button

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-hotgrid#4]
_From @shauncg on October 28, 2014 16:11_

Although I can see an appropriate-looking label on the close button for the hot grid DTs, when it is tabbed to JAWS simply reads "Accessibility underline test underline course underline 14 point 10 point 22 slash index link". For whatever reason it is reading part of the URL rather than the appropriate ARIA label.

_Copied from original issue: cgkineo/adapt_framework#24_

**Comment by moloko** [comment]
still relevant?
