### ISSUE TITLE
Verify this works with Adapt 4

### ISSUE THREAD

**Issue by tomgreenfield** [cgkineo/adapt-hotgrid#40]
Update the framework dependency if so.

**Comment by joe-replin** [comment]
Hello, I have installed the hotgrid to a v4 project and it is immediately usable. However, I had problems with the adapt-setup tool recognizing it as compatible with the v4 framework.

**Comment by moloko** [comment]
@joe-replin that should be resolved by a45df0583bdf0cafd2f004fe3daf814071892447#diff-0a08a7565aba4405282251491979bb6b
