### ISSUE TITLE
Error in popup code

### ISSUE THREAD

**Issue by chrisgillison** [cgkineo/adapt-hotgrid#43]
There seems to be an error [on this line here](https://github.com/cgkineo/adapt-hotgrid/blob/407d08bf71a50b07a413af751e8cb4f7a4f59526/templates/hotgridPopup.hbs#L16)
The popup image isn't loading. Think it should be '_itemGraphic'.

**Comment by moloko** [comment]
Good spot. We typically don't use a different image in the popup so this never appeared as a bug for us. I'll see about fixing it in a way that works for both.
