### ISSUE TITLE
Hotgrid notify (pop up) theme - revert to default

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-hotgrid#45]
Remove notify hotgrid overrides so that the pop up mirrors the default notify theme.

**Comment by moloko** [comment]
+1 as the new style popup is rubbish on small screens

If possible, it would be great if we could keep the 'pagination' feature in the standard Notify style popup...?

**Comment by guywillis** [comment]
As of v5 the Hotgrid popup mirrors the Hotgraphic popup.
