### ISSUE TITLE
Hot grid - focus does not shift to pop-up layer on open

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-hotgrid#5]
_From @shauncg on October 28, 2014 16:11_

When a hot grid DT is opened JAWS does not appear to notice. Hitting down (or equivalent) to read on through the content proceeds through the hot grid graphics, and only reaches the revealed DT once all images have been read. Ideally focus should shift in the same way as happens with hot graphics. 

_Copied from original issue: cgkineo/adapt_framework#23_

**Comment by moloko** [comment]
is this still relevant?
