### ISSUE TITLE
Hot grid - repetitive content being read; possible redundant tags

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-hotgrid#6]
_From @shauncg on October 28, 2014 16:11_

When JAWS reads through the hot grid, it will read first the alt text and then the title text for every image. At the moment this means it will read "Link Graphic Grid item alt text 1 Grid item 1 Link Graphic Grid item alt text 2 Grid item 2" and so on. 

Ideally only one of the two seems necessary. When the hot grid images are tabbed to the alt text is read, so can the title text be removed? 

_Copied from original issue: cgkineo/adapt_framework#22_

**Comment by moloko** [comment]
still relevant?
