### ISSUE TITLE
Adjusting semantic differentiation between status and heading

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-hotgrid#87]
### Subject of the issue/enhancement/features
A visited status is appended to the end of the aria-label string via innerHTML. Based on the changes recommend in the PR listed below, status indicators should come before the aria-label. I attempted to use insertAdjacentHTML to append the status to the label, but this resulted in the addition of unwanted quotation marks and line breaks within each component item aria-label. Is there a better way?

### Linked Issues
https://github.com/adaptlearning/adapt-contrib-core/issues/151
https://github.com/adaptlearning/adapt-contrib-core/pull/206

**Comment by kirsty-hames** [comment]
Hey @joe-replin, looks like this issue got addressed in the [ES6/JSX conversion and schema AAT updates PR](https://github.com/cgkineo/adapt-hotgrid/commit/e26a6471ac91d238af999053e10b46ec7dd02591). See screenshot below for course example.

<img width="1248" alt="visited_aria" src="https://github.com/cgkineo/adapt-hotgrid/assets/7045330/9cc172c4-0a4b-443a-b850-a82c64d642fb">

Are you happy to close this ticket?

**Comment by joe-replin** [comment]
Thanks for bringing this up, Kirsty. I will do so now.
